[default_config]
version = "0.10.0"
assembler = "gas"
instruction_set = "arm64"

[default_config.opts]
compiler = "aarch64-linux-gnu-gcc"
compile_flags_txt = []
diagnostics = true
default_diagnostics = false

# [[project]]
# path = "examples"
# version = "0.10.0"
# assembler = "gas"
# instruction_set = "arm64"
#
# [project.opts]
# compiler = "aarch64-linux-gnu-gcc"
# compile_flags_txt = []
# diagnostics = true
# default_diagnostics = false
